language: python

python:
    - "3.6"

script: python 9pm.py -d --option cmdl-supplied unit_tests/auto.yaml

addons:
    apt_packages:
      - python-yaml
      - tcl8.5
      - tcllib
      - expect

notifications:
    irc: "chat.freenode.net#9pm"
